version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo test
      - echo $CODEBUILD_GIT_AUTHOR
      - echo $CODEBUILD_WEBHOOK_TRIGGER
artifacts:
  files:
    - appspec.yml
  discard-paths: yes
